### ISSUE TITLE
What this repo is about?

### ISSUE THREAD

**Issue by ManasN** [JeffreyWay/laravel-mix-example#1]
This looks interesting!
I would really like a peek inside current Laravel 5.3's elixir's webpack magic and it seems like this repo sheds some light on it.
Please update the readme with more info.

**Comment by akitengineer** [comment]
This repo is just demonstration of the following repo. Jeff created this repo to show us example how to use laravel mix.

Please visit:
https://github.com/JeffreyWay/laravel-mix

**Comment by ManasN** [comment]
@akitengineer thanks for your kind words.
